from google.adk.agents.llm_agent import Agent

# 1. The Coordinator Agent: Fast routing and strategy formulation
coordinator_agent = Agent(
    name='coordinator_agent',
    model='gemini-2.5-flash',
    description='Manages workflow state and proposes high-level strategies.',
    instruction='You are the Coordinator. Evaluate user input. If asked for problem variants, propose distinct mathematical angles to alter the root problem, then instruct the Math Reasoning Agent to execute.',
)

# 2. The Math Reasoning Agent: Deep thinking, calculation, and generation
math_reasoning_agent = Agent(              
    name='math_reasoning_agent',
    model='gemini-2.5-pro',
    description='Handles complex mathematical problem solving and CoT generation.',
    instruction='You are an elite Math Expert. Use extreme mathematical rigor. Generate flawless step-by-step Chain-of-Thought solutions based on the strategy provided by the Coordinator.',
)

# 3. The Critic Agent: Validation and formatting
critic_agent = Agent(
    name='critic_agent',
    model='gemini-2.5-flash',
    description='Reviews mathematical outputs for errors and formats into strict JSON.',
    instruction='You are the Critic. Review the problems and solutions generated by the Math Reasoning Agent. Check for logical flaws or calculation errors. Output the final approved result in strict JSON format.',
)

# The root agent that the Runner attaches to, acting as the entry point
root_agent = coordinator_agent
